/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mylibrary_NDKString */

#ifndef _Included_com_example_mylibrary_NDKString
#define _Included_com_example_mylibrary_NDKString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mylibrary_NDKString
 * Method:    NDKFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_mylibrary_NDKString_NDKFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
